Added extra colorscheme setting functionality.
Lustbg now works with either 0, 1 or 2 arguments.

- if no arguments were passed, lustbg will set the colorscheme with the
dependency script `flust`.

- if one argument was passed, it will check if the argument is either a
path to an image file or if it's a path to a wallust colorscheme
template, and use the apply_colorscheme() or apply_wallpaper() functions
accordingly.

- if two arguments were passed, with the first argument being the path
to an image and the second argument being the path to a wallust
colorscheme template, it will set the image as an wallpaper using waybg
and set the wallust colorscheme that was given by the second argument.

diff --git a/.local/bin/lustbg b/.local/bin/lustbg
--- a/.local/bin/lustbg
+++ b/.local/bin/lustbg
@@ -1,14 +1,15 @@
 #!/usr/bin/env sh
 
 # Exit if necessary scripts aren't in PATH:
-if ! which waybg || ! which wallust || ! which wallust_postrun; then
+if ! which waybg || ! which wallust || ! which wallust_postrun || ! which flust; then
+	echo "ERROR: You don't have the required dependency in your PATH variable, make sure to install them correctly."
+	echo "Dependency scripts required: waybg, wallust, wallust_postrun, flust."
 	exit 1
 fi >/dev/null 2>&1
 
-file="$(dirname "$@")/$(basename "$@")"
-file_extension="$(basename -- "$file" | awk 'BEGIN { FS = "." } { print "." tolower($NF) }')"
-
-apply_colorscheme(){ wallust cs "$1" && wallust_postrun; }
+apply_colorscheme(){
+	wallust cs "$1" && wallust_postrun
+}
 
 apply_wallpaper(){
 	waybg "$1" &&
@@ -17,7 +18,24 @@ apply_wallpaper(){
 		wallust_postrun
 }
 
+# Change theme with flust if no arguments were given.
+if [ -z "$*" ]; then
+	theme="$(flust)"
+	[ -n "$theme" ] && wallust_postrun && exit 0
+fi
+
+# Change wallpaper and switch to specified colorscheme if two arguments were given.
+if [ -n "$2" ]; then
+	wallpaper="$(dirname -- "$1")/$(basename -- "$1")"
+	theme="$(dirname -- "$2")/$(basename -- "$2")"
+	waybg "$wallpaper" && apply_colorscheme "$theme" && exit 0
+fi
+
+# If only one argument was given, check if it's an wallpaper of a .json colorscheme file, and apply wallust theme accordingly.
+file="$(dirname "$1")/$(basename "$1")"
+file_extension="$(basename -- "$file" | awk 'BEGIN { FS = "." } { print "." tolower($NF) }')"
+
 case "$file_extension" in
 	'.json') apply_colorscheme "$file" ;;
-	*)       apply_wallpaper "$file"   ;;
+	*)       apply_wallpaper   "$file" ;;
 esac
