feat(bin/zel): improve codebase
Improved the codebase of the "zel" script so that certain bugs were
addressed and features were added.

feat(bin/zel): increase fzf list height

refactor(hypr): remove "FZF_DEFAULT_OPTS" manipulation

Removed the manipulation on the "$FZF_DEFAULT_OPTS" enviroment variable
when launching the 'zel' shell script from hyprland.

refactor(bin/zel): remove tab/pane auto renaming

Removed code related to renaming tabs and pane frames when creating a
new zellij session and it was not able to differentiate between sessions
that were already running in the past or sessions that have been created
with the script itself.

refactor(bin/zel): simplify fzf preview code

Simplified the code inside the fzf '--preview' flag by using early
returns on certain if statements.

refactor(bin/zel): remove "session" text from fzf preview

Removed the "session" text from the fzf preview when hovering over a
line on the fuzzy search that represents a zellij session.

fix(bin/zel): don't list currently active session

Prevent zel script from displaying the currently active zellij session
on the fzf fuzzy search list.

chore(bin/zel): remove unnecessary comments

refactor(bin/zel): update dir/session detection

refactor(bin/zel): remove useless tail

Removed an useless "tail -n1" call on the fzf selection by passing that
job to sed instead.

fix(bin/zel): prevent switch to active session

Fixed an issue where the `handle_sessions()` could try to switch to the
currently active session, which would make zellij thread panic.

refactor(bin/zel): better handle fzf output

Improved the handling of the fzf output by using the outputted icons as
a detection method for which type of functions should be used.

refactor(bin/zel): prevent unwanted output

Prevented some unwanted output from the `handle_sessions()` function
from being displayed in the terminal.

feat(bin/zel): improve directory session handling

feat(bin/zel): support git worktree session naming

fix(bin/zel): properly increase zoxide scores

Properly handled selected paths so that their score is increased on
zoxide's database.

fix(bin/zel): preview not working with fish

Fixed an issue were fzf preview wouldn't work if fish was set as the
user's default shell as that would change the "$SHELL" variable used by
fzf's --preview flag.

fix(bin/zel): add --ansi fzf flag

feat(bin/zel): support skim fuzzy finder

Support both skim and fzf as fuzzy finders.

feat(bin/zel): improve fuzzy picker styling

Improved the styling of the fuzzy picker window.

diff --git a/.local/bin/zel b/.local/bin/zel
--- a/.local/bin/zel
+++ b/.local/bin/zel
@@ -1,19 +1,26 @@
 #!/usr/bin/env sh
-
 # shellcheck disable=SC2016
 
-# Setup main variables.
+SESSION_PATH_SEP='|'
 ZELLIJ_SWITCH_PATH="${XDG_CONFIG_HOME:-${HOME}/.config}/zellij/plugins"
-
 if [ -n "${DISPLAY}" ]; then
-        DIRECTORY_ICON=''
-        SESSION_ICON='󰮊'
-        FZF_PROMPT='󰍉 Select Zellij Session: '
+        DIRECTORY_ICON=' '
+        SESSION_ICON='󰮊 '
+        PICKER_PROMPT='󰍉 Select Zellij Session: '
 else
-        DIRECTORY_ICON='D'
-        SESSION_ICON='S'
-        FZF_PROMPT='* Select Zellij Session: '
+        DIRECTORY_ICON='D '
+        SESSION_ICON='S '
+        PICKER_PROMPT='* Select Zellij Session: '
 fi
+
+fuzzy_finder() {
+        SHELL="$(which sh)" # This forces a posix shell to be used on preview panes.
+        if which fzf >/dev/null 2>&1; then
+                fzf "$@"
+        elif which sk >/dev/null 2>&1; then
+                sk "$@"
+        fi
+}
 
 install_zellij_switch() {
         printf '%s\n' \
@@ -31,21 +38,18 @@ install_zellij_switch() {
         mv -vf "${zellij_switch_tmp_dir}/target/wasm32-wasip1/release/zellij-switch.wasm" "${ZELLIJ_SWITCH_PATH}"
 }
 
-# Handle the creation/attachment of zellij sessions.
 handle_sessions() {
         session_name="${1}"
 
-        # This part checks if the session DOESN'T exist, and schedules pane/tab renaming actions for the session once it gets created.
-        session_exists="$(zellij ls --short 2>/dev/null | grep -i "${session_name}" 2>&1 | head -n1)"
-        [ -z "${session_exists}" ] && (
-                sleep 0.3
-                zellij --session "${session_name}" action rename-pane "${session_name}" && zellij --session "${session_name}" action rename-tab "${session_name}"
-        ) &
+        current_session="$(zellij ls --no-formatting 2>/dev/null | awk -F '[' '/\(current\)/ { gsub(/\s+/, ""); print $1 }' 2>/dev/null)"
+        [ "${session_name}" = "${current_session}" ] &&
+                echo 'ERROR: You cannot switch to the currently active session !!!' &&
+                exit 1
 
         if [ -z "${ZELLIJ}" ]; then
                 zellij attach --create "${session_name}"
         else
-                zellij attach --create-background "${session_name}"
+                zellij attach --create-background "${session_name}" 2>/dev/null
                 zellij pipe --plugin "file:${ZELLIJ_SWITCH_PATH}/zellij-switch.wasm" -- "--session ${session_name}"
         fi
 
@@ -53,48 +57,49 @@ handle_sessions() {
 }
 
 handle_dirs() {
-        session_path="${1}"
+        session_path="$(readlink -f -- "${1}")"
+        cd -- "${session_path}" || exit 1
+        zoxide add "${session_path}"
 
-        # This checks if there's a running session with a name similar to the name of the directory selected and attaches to it.
-        # e.g.: selecting `~/.config/nvim` with an already existing `nvim` session will attach to the `nvim` session instead of creating a new one.
-        directory_basename="$(basename "$(readlink -f -- "${session_path}")")"
-        zellij_basename_query="$(zellij ls --short 2>/dev/null | grep -i "${directory_basename}" 2>&1 | head -n1)"
-        [ -n "${zellij_basename_query}" ] && handle_sessions "${zellij_basename_query}"
+        PATH_BASENAME="$(basename "${session_path}")"
 
-        cd -- "$(readlink -f -- "${session_path}")" || exit 1
+        GIT_ROOT="$(git -C "${session_path}" rev-parse --show-toplevel 2>/dev/null)"
+        GIT_ROOT_BASENAME="$(basename "${GIT_ROOT}")"
 
-        # These lines handle the naming of the session, if the session directory happens to be inside a git repo,
-        # the name of the session will be "${git_root_basename}|${basename_of_session_directory}".
-        git_root_basename="$(basename "$(git rev-parse --show-toplevel 2>/dev/null)")"
-        session_path="${git_root_basename:-${directory_basename}}"
-        [ -n "${git_root_basename}" ] && [ "${directory_basename}" != "${git_root_basename}" ] && session_path="${session_path}|${directory_basename}"
+        GIT_WORKTREE_ROOT="$(git -C "${session_path}" rev-parse --git-common-dir 2>/dev/null)"
+        GIT_WORKTREE_ROOT_BASENAME="$(basename "${GIT_WORKTREE_ROOT}")"
 
-        handle_sessions "${session_path}"
+        if [ -n "${GIT_ROOT_BASENAME}" ]; then
+                session_name="${GIT_ROOT_BASENAME}${session_path#"${GIT_ROOT}"}"
+        elif [ -n "${GIT_WORKTREE_ROOT_BASENAME}" ]; then
+                session_name="${GIT_WORKTREE_ROOT_BASENAME}${session_path#"${GIT_WORKTREE_ROOT}"}"
+        else
+                session_name="${PATH_BASENAME}"
+        fi
+
+        session_name="$(echo "${session_name}" | sed "sI/I${SESSION_PATH_SEP}Ig")"
+        handle_sessions "${session_name}"
 }
 
-# This function is responsible for outputting all the lines of text that will be parsed to fzf.
-# These mainly include active zellij sessions and zoxide queried paths.
 fzf_contents() {
         # This awk command formats the output list from zellij ls so that:
-        # 1) The session icon appears green just like the zellij session names (\033[0;32m).
-        # 2) The text formatting is entirely reset at the end of the session icon (\033[0m).
-        # 3) Zellij's session names appear right after the session icon.
-        zellij ls 2>/dev/null | awk '{ print "'"\033[0;32m${SESSION_ICON} \033[0m"'" $0 }'
+        # 1) It does NOT print the line listing the currently active zellij session `!/\(current\)/`
+        # 2) The session icon appears green just like the zellij session names `\033[0;32m`.
+        # 3) The text formatting is entirely reset at the end of the session icon `\033[0m`.
+        # 4) Zellij's session names appear right after the session icon.
+        zellij ls 2>/dev/null | awk '!/\(current\)/ { print "'"\033[0;32m${SESSION_ICON}\033[0m"'" $0 }'
 
         # This awk command formats the output list from zoxide query so that:
-        # 1) Replaces all the "$HOME" instances with "~".
-        # 2) Directory icon appears blue (\033[0;34m).
-        # 3) The text from the list is bold (\033[0;1m).
-        # 4) The text formatting is entirely reset at the end of every list item (\033[0m).
+        # 1) Replaces all the `$HOME` instances with `~`.
+        # 2) Directory icon appears blue `\033[0;34m`.
+        # 3) The text from the list is bold `\033[0;1m`.
+        # 4) The text formatting is entirely reset at the end of every list item `\033[0m`.
         zoxide query -l | awk '{
                 gsub("'"${HOME}"'", "~");
-                print "'"\033[0;34m${DIRECTORY_ICON} \033[0;1m"'" $0 "\033[0m"
+                print "'"\033[0;34m${DIRECTORY_ICON}\033[0;1m"'" $0 "\033[0m"
         }'
 }
 
-# Fzf cannot preview the contents of zellij sessions when hovering over
-# their name in the fuzzy picker, this function outputs some text
-# so that the preview window isnt empty.
 fzf_session_preview() {
         if [ -n "${DISPLAY}" ]; then
                 cat <<-EOF_DISPLAY
@@ -104,12 +109,6 @@ fzf_session_preview() {
  ███╔╝  ██╔══╝  ██║     ██║     ██║██   ██║
 ███████╗███████╗███████╗███████╗██║╚█████╔╝
 ╚══════╝╚══════╝╚══════╝╚══════╝╚═╝ ╚════╝
-███████╗███████╗███████╗███████╗██╗ ██████╗ ███╗   ██╗
-██╔════╝██╔════╝██╔════╝██╔════╝██║██╔═══██╗████╗  ██║
-███████╗█████╗  ███████╗███████╗██║██║   ██║██╔██╗ ██║
-╚════██║██╔══╝  ╚════██║╚════██║██║██║   ██║██║╚██╗██║
-███████║███████╗███████║███████║██║╚██████╔╝██║ ╚████║
-╚══════╝╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝
 EOF_DISPLAY
         else
                 cat <<-EOF_TTY
@@ -124,67 +123,60 @@ EOF_TTY
 }
 
 get_selected_session() {
-        # Display the fuzzy finder will all active sessions and zoxide paths.
-        selected_session="$(fzf_contents | fzf --print-query --prompt "${FZF_PROMPT}" --preview "
-                grep_check=\"\$(echo {} | grep '^${SESSION_ICON}')\"
-                if [ -n \"\${grep_check}\" ]; then
-                        printf '%s\n' \"$(fzf_session_preview)\"
-                        return 0
-                fi
-
-                # This huge awk command is just a fancier way of doing cut -d' ' -f2- | sed 's|~|${HOME}|g'
-                directory_path=\$(echo {} | awk -F ' ' -v n=2 '{ gsub(/~/, \"${HOME}\"); for (i=n; i<=NF; i++) printf \"%s%s\", \$i, (i<NF ? OFS : ORS) }')
-                directory_path=\$(readlink -f -- \"\${directory_path}\")
-
-                if ! which eza >/dev/null 2>&1; then
-                        if which tree >/dev/null 2>&1; then
-                                tree --dirsfirst --gitignore -aFC -L 3 \"\${directory_path}\"
+        SHELL="$(which sh)"
+        selected_session="$(fzf_contents | fuzzy_finder \
+                --ansi \
+                --info=inline \
+                --height=~100% \
+                --print-query \
+                --prompt "${PICKER_PROMPT}" \
+                --preview-window=up:7 \
+                --preview "
+                        grep_check=\"\$(echo {} | grep '^${SESSION_ICON}')\"
+                        if [ -n \"\${grep_check}\" ]; then
+                                printf '%s\n' \"$(fzf_session_preview)\"
                                 return 0
                         fi
 
-                        ls --group-directories-first --color=always -1A \${directory_path}
+                        # This huge awk command is just a fancier way of doing cut -d' ' -f2- | sed 's|~|${HOME}|g'
+                        directory_path=\$(echo {} | awk -F ' ' -v n=2 '{ gsub(/~/, \"${HOME}\"); for (i=n; i<=NF; i++) printf \"%s%s\", \$i, (i<NF ? OFS : ORS) }')
+                        directory_path=\$(readlink -f -- \"\${directory_path}\")
+
+                        if ! which eza >/dev/null 2>&1; then
+                                ls --group-directories-first --color=always -CA \"\${directory_path}\" || return 1
+                                return 0
+                        fi
+
+                        if [ -z \"\${DISPLAY}\" ]; then
+                                eza --group-directories-first --color=always --git-ignore -a \"\${directory_path}\" || return 1
+                        else
+                                eza --group-directories-first --color=always --git-ignore --icons -a \"\${directory_path}\" || return 1
+                        fi
                         return 0
-                fi
+        ")"
 
-                if [ -z \"\${DISPLAY}\" ]; then
-                        eza --group-directories-first --color=always --git-ignore --tree -a -L 3 \"\${directory_path}\"
-                else
-                        eza --group-directories-first --color=always --git-ignore --tree --icons -a -L 3 \"\${directory_path}\"
-                fi
-        " | tail -n1)"
-
-        # Exit if no directory nor active session was choosen.
         [ -z "${selected_session}" ] && exit 1
-
-        # Generate a proper input variable for the 'attach_to_session()' function based on the output of fzf_selector().
-        selected_session="$(echo "${selected_session}" | sed "
-                        s/^${DIRECTORY_ICON}\s\+//;
-                        s/^${SESSION_ICON}\s\+//;
-                        s|~|${HOME}|;
-                        s/\s\+\[.*//g")"
-
-        echo "${selected_session}"
+        echo "${selected_session}" | sed '$!d; s|~|'"${HOME}"'|; s/\s\+\[.*//g'
 }
 
 main() {
-        # This script depends on the 'zellij-switch' plugin to switch sessions while inside of a running zelllij session.
+        # This script depends on the `zellij-switch` plugin to switch sessions while inside of a running zelllij session.
         [ ! -f "${ZELLIJ_SWITCH_PATH}/zellij-switch.wasm" ] && install_zellij_switch
 
-        # Set session name to be the user input if any was given, otherwise fallback to fzf selection.
-        user_input="${1}"
+        user_input="$*"
         session_name="${user_input:-$(get_selected_session)}"
         [ -z "${session_name}" ] && exit 1
 
-        # If the selected session already exists inside of zellij, handle it's attachment with the `handle_sessions()` function.
-        zellij_session_query="$(zellij ls --short 2>/dev/null | grep -i "${session_name}" 2>&1 | head -n1)"
-        [ -n "${zellij_session_query}" ] && handle_sessions "${zellij_session_query}"
-
-        # If the user input matches a zoxide query, handle the queried path with the `handle_dirs()` function.
-        [ -n "${user_input}" ] && zoxide_query="$(zoxide query "${user_input}" 2>/dev/null)"
-        [ -n "${zoxide_query}" ] && handle_dirs "${zoxide_query}"
-
-        # If the session selected with fzf is a directory path, handle it with the `handle_dirs()` function.
-        [ -d "${session_name}" ] && handle_dirs "${session_name}"
+        session_icon="$(echo "${session_name}" | sed "s/^${SESSION_ICON}.*/${SESSION_ICON}/g; s/^${DIRECTORY_ICON}.*/${DIRECTORY_ICON}/g")"
+        case "${session_icon}" in
+        "${DIRECTORY_ICON}") handle_dirs "${session_name#"${DIRECTORY_ICON}"}" ;;
+        "${SESSION_ICON}") handle_sessions "${session_name#"${SESSION_ICON}"}" ;;
+        # If this case is run, it means the user put some string on the fzf prompt in order to create a new session.
+        *)
+                session_name="${session_icon}"
+                handle_sessions "${session_name}"
+                ;;
+        esac
 }
 main "$@"
 
