refactor(shell/functions/): Moved function definitions to aliasrc.

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -81,3 +81,41 @@ else
 		eza='eza --group-directories-first --color=always --icons'
 fi
 #: }}}
+#: Functions {{{
+up(){
+	local d=""
+	local limit="$1"
+
+	# Default to limit of 1.
+	if [ -z "$limit" ] || [ "$limit" -le 0 ]; then local limit=1; fi
+	for ((i=1; i<=limit; i++)); do local d="../$d"; done; unset i
+
+	# Perform cd. Show error if cd fails.
+	if ! builtin cd "$d"; then echo "Couldn't go up $limit dirs."; fi
+}
+
+alias \
+	yazi='yazicd' \
+	y='yazicd' \
+	yi='cdi && yazicd'
+
+yazicd(){
+	local cwd
+	local exited_path
+	local zoxide_query
+
+	exited_path="$(mktemp -t "yazi_cwd.XXXXXXXXXX")"
+
+	if zoxide_query="$(zoxide query -- "${@:-/dev/null}" 2>/dev/null)"; then
+		builtin cd -- "$zoxide_query" || :
+	fi
+
+	STARSHIP_CONFIG="/dev/null" command yazi --cwd-file="$exited_path" "${*:-"$(pwd)"}"
+
+	if cwd="$(< "$exited_path")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
+		builtin cd -- "$cwd" || return 1
+	fi
+
+	rm -rf -- "$exited_path" >/dev/null 2>&1
+}
+#: }}}
