enhance(git/commit-msg): use git-sumi
Enhanced the global git/commit-msg hook to make use of 'git-sumi'
(See: https://sumi.rs)

diff --git a/.config/git/hooks/commit-msg b/.config/git/hooks/commit-msg
--- a/.config/git/hooks/commit-msg
+++ b/.config/git/hooks/commit-msg
@@ -1,149 +1,78 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-SUBJECT_CHAR_LIMIT=72
-BODY_CAN_BE_EMPTY="${BODY_CAN_BE_EMPTY:-true}"
-UPPERCASE_BYPASS="${UPPERCASE_BYPASS:-true}"
+# Modified commit-msg hook generated by git-sumi.
+# For more information and documentation, visit: https://sumi.rs
 
-COMMIT_FILE="$1"
-COMMIT_SUBJECT="$(head -n1 "$COMMIT_FILE")"
-COMMIT_BODY="$(tail -n+2 "$COMMIT_FILE" | sed '/^#/d')"
+set -e # Exit on any error.
 
-VALID_COMMIT_TYPES='build chore ci docs feat fix perf refactor revert style test'
-VALID_COMMIT_TYPES="$(echo "$VALID_COMMIT_TYPES" | sed 's/ /\\|/g')"
-VALID_COMMIT_TYPES="^\(${VALID_COMMIT_TYPES}\)"
+# Main linting options:
+MAX_HEADER_LENGHT=50
+MAX_BODY_LENGHT=72
+# EXCLUDE_BRANCHES="main,master" # Exclude running git-sumi linting on these branches (leave empty for no exclusion).
+BODY_CAN_BE_EMPTY=false # True if commit body can be empty.
+UPPERCASE_BYPASS=false  # Commit messages that begins uppercase will bypass linting.
+VALID_COMMIT_TYPES="build,ci,chore,docs,feat,fix,perf,refactor,revert,style,test,enhance,improvement"
 
-# Format body of commit message.
-format_commit() {
-	if [ "$ERROR_COUNT" -gt 0 ]; then
-		echo ''
-		echo "Found ${ERROR_COUNT} errors with your commit message."
-
-		cat <<-EOF
-			Make sure your commit message follows the following commit rules:
-
-			1- Limit the subject line to 50 characters.
-			2- Separate subject from the body with a blank line (done automatically).
-			3- Do not capitalize any letter from subject line.
-			4- Do not end the subject line with a period.
-			5- Use the imperative mood in the subject line.
-			6- Wrap the body at 72 characters (done automatically).
-			7- Use the body to explain what and why vs. how.
-			8- The commit message should obey the following commit structure:
-
-			[type(optional scope)optional "!"]: subject]
-
-			[optional body]
-
-			scope is optional; Currently supported scope delimiters are: "/", "\" and ","
-
-			note that body can only be optionally empty if the enviroment variable
-			BODY_CAN_BE_EMPTY is set to true when the script runs. Otherwise
-			an extra linting check will be performed to make sure the body is not empty.
-
-			Here are the supported commit types:
-			- build    -> Build system or external dependencies changes.
-			- chore    -> Maintenance changes.
-			- ci       -> CI configurations and script changes.
-			- docs     -> Documentation changes.
-			- feat     -> Addition of a new feature.
-			- fix      -> Bug fix.
-			- perf     -> Performance improvements.
-			- refactor -> Neither fixes a bug or adds a feature.
-			- revert   -> Reverts a previous commit.
-			- style    -> Formatting, missing semi colons, etc.
-			- test     -> Adding missing tests.
-		EOF
-
-		exit 1
-	fi
-
-	tmp_commit_file="$(mktemp)"
-	trap 'rm -rf "${tmp_commit_file}"' 0 1 15
-
-	echo "$COMMIT_SUBJECT" >"$tmp_commit_file"
-
-	if [ -n "$(head -n2 "$COMMIT_FILE" | tail -n1)" ]; then
-		echo '' >>"$tmp_commit_file"
-	fi
-
-	echo "$COMMIT_BODY" | fold --spaces --width=72 >>"$tmp_commit_file"
-
-	cat "$tmp_commit_file" >"$COMMIT_FILE"
-}
-
-ERROR_COUNT=0
-echoerr() {
-	ERROR_COUNT="$((ERROR_COUNT + 1))"
-
-	message="$1"
-	if [ -z "$DISPLAY" ]; then
-		error_char='ERROR:'
-	else
-		error_char='󱎘'
-	fi
-
-	echo "$(tput setaf 1 bold)${error_char} $(tput sgr0)${message}"
-}
-
-check() {
-	CHECK_STR=''     # Reset previous CHECK_STR.
-	ERROR_MESSAGE='' # Reset previous ERROR_MESSAGE.
-
-	CHECK_STR="$1"
-	ERROR_MESSAGE="$2"
-
-	if echo "$COMMIT_SUBJECT" | grep -q "${CHECK_STR}"; then
-		echoerr "$ERROR_MESSAGE"
-	fi
-}
-
-not_check() {
-	CHECK_STR=''     # Reset previous CHECK_STR.
-	ERROR_MESSAGE='' # Reset previous ERROR_MESSAGE.
-
-	CHECK_STR="$1"
-	ERROR_MESSAGE="$2"
-
-	if ! echo "$COMMIT_SUBJECT" | grep -q "${CHECK_STR}"; then
-		echoerr "$ERROR_MESSAGE"
-	fi
-}
-
-# Check if subject lenght = 0 or > 50 characters long.
-COMMIT_SUBJECT_LENGHT="$(head -n1 "$COMMIT_FILE")"
-if [ "${#COMMIT_SUBJECT_LENGHT}" -eq 0 ]; then
-	echoerr 'subject cannot be empty'
+# Check if git-sumi is installed.
+if ! command -v git-sumi &>/dev/null; then
+	echo "git-sumi is not installed. Please install it. See https://sumi.rs for instructions."
+	echo "Alternatively, edit or remove the commit-msg hook in .git/hooks/commit-msg."
 	exit 1
-elif [ "${SUBJECT_CHAR_LIMIT}" -gt 0 ] && [ "${#COMMIT_SUBJECT_LENGHT}" -gt "${SUBJECT_CHAR_LIMIT}" ]; then
-	echoerr "subject cannot be longer than '${SUBJECT_CHAR_LIMIT}' characters."
 fi
 
-# Perform empty body check only if $BODY_CAN_BE_EMPTY = false.
-if [ "$BODY_CAN_BE_EMPTY" != true ] && [ -z "$COMMIT_BODY" ]; then
-	echoerr "body cannot be empty. (to allow it set 'BODY_CAN_BE_EMPTY' to true)"
+# Main variables:
+commit_file="${1}"
+commit_header="$(head -n1 "${commit_file}")"
+commit_body="$(tail -n+2 "${commit_file}" | sed '/^#/d')"
+
+# Bypass linting if the current branch is not 'main' or 'master'.
+if [ -n "${EXCLUDE_BRANCHES}" ]; then
+	current_branch=$(git rev-parse --abbrev-ref HEAD)
+
+	for branch in ${EXCLUDE_BRANCHES//,/ }; do
+		if [ "${branch}" == "${current_branch}" ]; then
+			exit 0
+		fi
+	done
 fi
 
-if echo "$COMMIT_FILE" | grep -q 'MERGE_MSG' || echo "$COMMIT_SUBJECT" | grep -q '^Merge'; then
-	format_commit
+# Bypass linting if uppercase bypass is enabled.
+if [ "${UPPERCASE_BYPASS}" = true ] && echo "${commit_header}" | grep -q '^[A-Z]'; then
 	exit 0
 fi
 
-if [ "$UPPERCASE_BYPASS" = true ] && echo "$COMMIT_SUBJECT" | grep -q '^[A-Z]'; then
-	format_commit
-	exit 0
+# Perform empty body check if needed.
+if [ "${BODY_CAN_BE_EMPTY}" != true ] && [ -z "${commit_body}" ]; then
+	echo "❌ Body cannot be empty."
+	exit 1
 fi
 
-check "${VALID_COMMIT_TYPES}!\?:[[:space:]]\?[A-Z]\+\|${VALID_COMMIT_TYPES}(.*)!\?:[[:space:]]\?[A-Z]\+" 'subject cannot start with upper case characters.'
-check '\.$' 'subject cannot end with a period.'
-not_check "${VALID_COMMIT_TYPES}!\?:.*\|${VALID_COMMIT_TYPES}(.*)!\?:.*" 'invalid commit type.'
-check "${VALID_COMMIT_TYPES}([^)]*!\?:.*" 'scope was never closed.'
-check "${VALID_COMMIT_TYPES}()" 'scope cannot be empty.'
-check "${VALID_COMMIT_TYPES}([,\/].*)!\?:.*" 'scope cannot begin with a delimiter.'
-check "${VALID_COMMIT_TYPES}(.*[,\/])!\?:.*" 'scope cannot end with a delimiter.'
-check "${VALID_COMMIT_TYPES}(.*\.)!\?:.*" 'scope cannot end with a period.'
-not_check "${VALID_COMMIT_TYPES}!\?:.*\|${VALID_COMMIT_TYPES}(.*)!\?:.*" "'!' and ':' are the only valid characters after scope."
-check "${VALID_COMMIT_TYPES}!\?:[^[:space:]].*\|${VALID_COMMIT_TYPES}(.*)!\?:[^[:space:]].*" "must add space after ':'."
+# Format commit file:
+tmp="$(mktemp)"
+trap 'rm -rf "${tmp}"' 0 1 15
 
-format_commit
+# Add commit header to tmp file.
+echo "${commit_header}" >"$tmp"
 
-# vim:fileencoding=utf-8:foldmethod=marker
+# Add space betwheen commit header and body if needed.
+if [ -n "$(head -n2 "${commit_file}" | tail -n1)" ]; then
+	echo '' >>"$tmp"
+fi
+
+# Fold commit body to make it no longer then the maximum specified body length.
+echo "${commit_body}" | fold --spaces --width="${MAX_BODY_LENGHT}" >>"$tmp"
+
+# Remove trainling whitespaces and apply changes to original commit file.
+sed 's/[ \t]*$//' "$tmp" >"$commit_file"
+
+# Lint formatted commit file:
+git-sumi --display \
+	--conventional \
+	--imperative \
+	--whitespace \
+	--description-case "lower" \
+	--no-period \
+	--max-header-length "${MAX_HEADER_LENGHT}" \
+	--max-body-length "${MAX_BODY_LENGHT}" \
+	--types-allowed "${VALID_COMMIT_TYPES}" \
+	-- "$(cat "${commit_file}")" # Exits with error if linting fails.
